/*

Giga-CAD Plus 3D object converter to Wavefront OBJ

MIT License

Copyright 2019 Josef Soucek
<josef at ide64 dot org>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/

#include <stdio.h>
#include <stdlib.h>

// Prototypes

int getasciinum(FILE *);
float getrealnum(FILE *);

typedef struct point {
  float x;
  float y;
  float z;
  } Points;

typedef struct polygon {
  int i;
  unsigned char attr;
  } Polygons;

int main(int argc, char *argv[])
{
  FILE *fp;
  char *filename;
  char ch;
  int num_ver, num_fac, num_mac;
  int i,j;
  Polygons face[1500];
  unsigned char lownum,highnum;
  Points vertex[1500];

  if (argc < 2)
  {
        printf("Giga-CAD Plus 3D object converter to Wavefront OBJ\n");
        printf("https://github.com/mrjoso/giga-cad-obj\n\n");
        printf("Usage: objconv.exe inputfile [outputfile]\n");
        printf("\nVersion 1.0, Released in 2019\n");
        return(1);
  } else {

        filename = argv[1];
        printf("Filename : %s\n", filename);
  }

  // Open file in read-only mode
  fp = fopen(filename,"r");

   // If file opened successfully
  if ( fp ) {

// #### START #### 
       
    num_fac = getasciinum(fp);
    num_ver = getasciinum(fp);
    num_mac = getasciinum(fp);

    printf("faces:%d \nvertices:%d \nmacros:%d\n",num_fac,num_ver,num_mac);       
  
    ch = fgetc(fp); printf("1. %02x\n", (unsigned char)ch);
    ch = fgetc(fp); printf("2. %02x\n", (unsigned char)ch);
    ch = fgetc(fp); printf("3. %02x\n", (unsigned char)ch);

// FACES
   
    for (i=1; i<num_fac; i++) {
      lownum = fgetc(fp);   // low
      highnum = fgetc(fp);  // high
      face[i].attr = fgetc(fp);     // atribut

      face[i].i = lownum + highnum * 256;

      printf("[%d] face index:%d attr: %02x\n",i,face[i].i, face[i].attr);       
    }
    face[i].i = 0xfff; // Higher number than existing vertex

    ch = fgetc(fp); printf("1. %02x\n", (unsigned char)ch);
    ch = fgetc(fp); printf("2. %02x\n", (unsigned char)ch);
    ch = fgetc(fp); printf("3. %02x\n", (unsigned char)ch);

    ch = fgetc(fp); printf("4. %02x\n", (unsigned char)ch);
    ch = fgetc(fp); printf("5. %02x\n", (unsigned char)ch);
    ch = fgetc(fp); printf("6. %02x\n", (unsigned char)ch);

// VERTICES
   
    for (i=1; i<=num_ver; i++) {

      vertex[i].x = getrealnum(fp);
      vertex[i].y = getrealnum(fp);
      vertex[i].z = getrealnum(fp);

      printf("[%d] X: %f Y: %f Z: %f \n",i,vertex[i].x,vertex[i].y,vertex[i].z);       
    }

// END OF IMPORT

    printf("Macros:\n");
    while ((ch = fgetc(fp)) != EOF )
    {
      if (ch == 0x0d) printf("\n");
      else printf("%c",ch);
    }
    printf("\n");

    fclose(fp);

// EXPORT TO .obj FILE

    if (argc < 3 ) filename = "object.obj";
    else filename = argv[2];

    printf("Output : %s\n", filename);

    // Open file in write mode
    fp = fopen(filename,"w");

    // If file opened successfully
    if ( fp ) {

// WRITE CONTENT

// HEADER

      fprintf(fp,"####\n");       
      fprintf(fp,"#\n");       
      fprintf(fp,"# Wavefront OBJ File Generated by Giga-CAD Plus 3D object converter\n"); 
      fprintf(fp,"#\n");       
      fprintf(fp,"####\n");       
      fprintf(fp,"# Object %s\n",argv[1]);
      fprintf(fp,"#\n");       
      fprintf(fp,"# Vertices: %d\n",num_ver);
      fprintf(fp,"# Polygon rings: %d\n",num_fac-1);
      fprintf(fp,"#\n");       
      fprintf(fp,"####\n");       

// Vertices

      for (i=1; i<=num_ver; i++) {
        fprintf(fp,"v %f %f %f\n",vertex[i].x,vertex[i].y,vertex[i].z);       
      }

// Faces

      for (i=1; i<num_fac; i++) {

// Polygon consists of two or more rings

// Check - if there is a Polygon with hole or multipolygon
// if yes (typically polygon with a hole), create bridge edge
// and add it to the same face definition
// Giga-CAD Plus does not differentiate inner and outer rings
// This solution has problems and may produce incorrect faces (self intersecting etc.)

        if ((face[i].attr & 0x80) != 0) {
          fprintf(fp," %d",face[i-1].i);
          printf("[%d] Warning, one more ring in a polygon\n",i);

        } else {
          fprintf(fp,"\nf");
        }
          for(j=face[i].i; j<face[i+1].i; j++) {
            if (j > num_ver) break;
            fprintf(fp," %d",j);       
          }
        if ((face[i].attr & 0x80) != 0 && (face[i+1].attr & 0x80) == 0) {
          fprintf(fp," %d",face[i].i);
        } 

      } // for

    } else {
      printf("Failed to write the file\n");
    }
  
    fclose(fp);

   } else {
     printf("Failed to open the file\n");
   }

return(0);
}

int getasciinum(FILE *fp)
{
  int i;
  char ch;
  char num[10];

  for (i=0; (ch = fgetc(fp)) != 0x0d; i++) num[i]=ch;
  num[i]=0;
  return (atoi(num));
}

float getrealnum(FILE *fp)
{
  unsigned char lownum, highnum;
  int16_t converted;
  float re=0;

  lownum = fgetc(fp);

  if ((lownum & 0x01) != 0) re+=0.0625;
  if ((lownum & 0x02) != 0) re+=0.125;
  if ((lownum & 0x04) != 0) re+=0.25;
  if ((lownum & 0x08) != 0) re+=0.5;

// positive or negative is the same
// 2^-1 2^-2 2^-3 2^-4
//0.875   0x0e %1110
//0.75    0x0c %1100
//0.5     0x08
//0.25    0x04
//0.125   0x02
//0.0625

  highnum = fgetc(fp); 
  converted = (lownum + highnum * 256)>>4;

// Two's Complement
// High bit = 1 mean negative

  if ((converted & 0x800) != 0) {
    converted |= 0xf000;
    converted = ~converted;
    converted += 1;
    converted *= -1;
  }
  re += converted;
  return (re);
}

